"""
PDF Report Generation Service.

Compiles a highly polished, executive-level multi-page PDF document representing the
candidate's cybersecurity career assessment, Digital Twin persona, live market insights,
and learning roadmap. Built using ReportLab flowables.
"""

import math
import logging
from io import BytesIO
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.lib.colors import Color, HexColor
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, KeepTogether, PageBreak
from reportlab.pdfgen import canvas
from reportlab.graphics.shapes import Drawing, Rect, Polygon, Line, String

from app.services.skill_gap_service import compute_skill_gap
from app.services.readiness_score_service import compute_readiness_score
from app.services.learning_roadmap_service import generate_roadmap
from app.services.radar_chart_service import compute_radar_data
from app.utils.taxonomy_loader import load_roles_taxonomy
from app.utils.exceptions import NotFoundError

logger = logging.getLogger(__name__)


# ── Numbered Canvas Wrapper for Multi-Page Header & Footer ────────────────────

class NumberedCanvas(canvas.Canvas):
    """Custom canvas that performs two-pass rendering to draw headers, footers, and page counts."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()

        slate_color = Color(71/255.0, 85/255.0, 105/255.0)     # #475569
        border_color = Color(226/255.0, 232/255.0, 240/255.0)  # #e2e8f0

        # Draw header on all pages except the cover page
        if self._pageNumber > 1:
            self.setFont("Helvetica-Bold", 8)
            self.setFillColor(HexColor("#4F46E5"))
            self.drawString(54, 750, "CareerPilot AI — Executive Cybersecurity Intelligence Report")
            self.setStrokeColor(border_color)
            self.setLineWidth(0.5)
            self.line(54, 742, 558, 742)

        # Draw footer on all pages
        self.setStrokeColor(border_color)
        self.setLineWidth(0.5)
        self.line(54, 45, 558, 45)

        self.setFont("Helvetica", 8)
        self.setFillColor(slate_color)
        timestamp = datetime.now().strftime("%B %d, %Y • %H:%M UTC")
        self.drawString(54, 30, f"Generated by CareerPilot AI v2.0 | {timestamp}")

        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 30, page_str)

        self.restoreState()


# ── Vector Drawing Helpers ───────────────────────────────────────────────────

def draw_pdf_progress_bar(coverage_pct: int) -> Drawing:
    """Render a clean progress bar using ReportLab shapes."""
    d = Drawing(450, 14)
    d.add(Rect(0, 0, 450, 14, fillColor=HexColor("#F1F5F9"), strokeColor=None, rx=4, ry=4))
    filled_width = max(0, min(450, 450 * (coverage_pct / 100.0)))
    if filled_width > 0:
        d.add(Rect(0, 0, filled_width, 14, fillColor=HexColor("#4F46E5"), strokeColor=None, rx=4, ry=4))
    return d


def draw_pdf_radar_chart(candidate_scores: list[int], required_scores: list[int], labels: list[str]) -> Drawing:
    """Draw a vector skill radar chart directly using ReportLab shapes."""
    d = Drawing(300, 220)
    cx, cy = 150, 105
    r_max = 75

    for scale in [0.2, 0.4, 0.6, 0.8, 1.0]:
        points = []
        for i in range(6):
            angle = i * (2 * math.pi / 6)
            rx = cx + (r_max * scale) * math.cos(angle)
            ry = cy + (r_max * scale) * math.sin(angle)
            points.extend([rx, ry])
        d.add(Polygon(points, strokeColor=HexColor("#CBD5E1"), fillColor=None, strokeWidth=0.5))

    for i, label in enumerate(labels):
        angle = i * (2 * math.pi / 6)
        rx = cx + r_max * math.cos(angle)
        ry = cy + r_max * math.sin(angle)
        d.add(Line(cx, cy, rx, ry, strokeColor=HexColor("#CBD5E1"), strokeWidth=0.5))

        lx = cx + (r_max + 12) * math.cos(angle)
        ly = cy + (r_max + 6) * math.sin(angle)

        if math.cos(angle) < -0.1:
            lx -= len(label) * 4
        elif abs(math.cos(angle)) < 0.1:
            lx -= len(label) * 2

        d.add(String(lx, ly - 3, label, fontSize=7.5, fontName="Helvetica-Bold", fillColor=HexColor("#475569")))

    req_points = []
    for i, score in enumerate(required_scores):
        angle = i * (2 * math.pi / 6)
        val = max(0, min(100, score))
        rx = cx + (r_max * (val / 100.0)) * math.cos(angle)
        ry = cy + (r_max * (val / 100.0)) * math.sin(angle)
        req_points.extend([rx, ry])
    d.add(Polygon(req_points, strokeColor=HexColor("#6366F1"), fillColor=Color(99/255.0, 102/255.0, 241/255.0, alpha=0.15), strokeWidth=1.5))

    cand_points = []
    for i, score in enumerate(candidate_scores):
        angle = i * (2 * math.pi / 6)
        val = max(0, min(100, score))
        rx = cx + (r_max * (val / 100.0)) * math.cos(angle)
        ry = cy + (r_max * (val / 100.0)) * math.sin(angle)
        cand_points.extend([rx, ry])
    d.add(Polygon(cand_points, strokeColor=HexColor("#10B981"), fillColor=Color(16/255.0, 185/255.0, 129/255.0, alpha=0.25), strokeWidth=1.5))

    return d


# ── PDF Build Engine ─────────────────────────────────────────────────────────

def generate_pdf_report(
    role_id: str,
    skills: list[str],
    name: str,
    email: str,
    phone: str,
    summary: str,
    exp_titles: list[str],
    exp_descriptions: list[str],
    exp_durations: list[str],
    edu_degrees: list[str],
    cert_names: list[str]
) -> bytes:
    """Generate a compiled multi-page executive PDF report."""
    logger.info("Compiling executive PDF report for name=%s, role_id=%s", name, role_id)

    skill_gap = compute_skill_gap(skills, role_id)
    readiness = compute_readiness_score(
        role_id, skills, exp_titles, exp_descriptions, exp_durations, edu_degrees, cert_names
    )
    roadmap = generate_roadmap(skills, role_id)
    radar = compute_radar_data(skills, role_id)

    raw_roles = load_roles_taxonomy()
    target_role = next((r for r in raw_roles if r.get("id") == role_id), None)
    if not target_role:
        target_role = raw_roles[0] if raw_roles else {
            "id": role_id,
            "name": "SOC Analyst L2",
            "description": "Security Operations Specialist",
            "required_skills": [],
            "certifications": ["CompTIA Security+"]
        }

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=64
    )

    base_styles = getSampleStyleSheet()

    cover_title_style = ParagraphStyle(
        'CoverTitle',
        parent=base_styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=30,
        leading=34,
        textColor=HexColor("#1E1B4B"),
        spaceAfter=8
    )
    cover_subtitle_style = ParagraphStyle(
        'CoverSubtitle',
        parent=base_styles['Normal'],
        fontName='Helvetica',
        fontSize=13,
        leading=17,
        textColor=HexColor("#4F46E5"),
        spaceAfter=30
    )
    section_h1_style = ParagraphStyle(
        'SectionH1',
        parent=base_styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=13,
        leading=16,
        textColor=HexColor("#4F46E5"),
        spaceBefore=14,
        spaceAfter=10,
        keepWithNext=True
    )
    body_style = ParagraphStyle(
        'BodyDark',
        parent=base_styles['BodyText'],
        fontName='Helvetica',
        fontSize=9,
        leading=13,
        textColor=HexColor("#334155")
    )
    bold_label_style = ParagraphStyle(
        'BoldLabel',
        parent=body_style,
        fontName='Helvetica-Bold',
        textColor=HexColor("#0F172A")
    )

    story = []

    # ── COVER PAGE ────────────────────────────────────────────────────────────
    story.append(Spacer(1, 40))
    story.append(Paragraph("CareerPilot AI", cover_title_style))
    story.append(Paragraph("AI-Powered Cybersecurity Career Intelligence Platform", cover_subtitle_style))
    story.append(Spacer(1, 20))

    meta_table_data = [
        [Paragraph("Candidate Name:", bold_label_style), Paragraph(name or "Samuel Godson", body_style)],
        [Paragraph("Email Address:", bold_label_style), Paragraph(email or "samuel@example.com", body_style)],
        [Paragraph("Report Generated:", bold_label_style), Paragraph(datetime.now().strftime("%B %d, %Y"), body_style)],
        [Paragraph("Resume Version:", bold_label_style), Paragraph("v2.0 (Neural Parsed Telemetry)", body_style)],
        [Paragraph("Target Role:", bold_label_style), Paragraph(target_role.get("name", "SOC Analyst L2"), bold_label_style)],
        [Paragraph("Report Type:", bold_label_style), Paragraph("AI Digital Twin Career Telemetry Executive Summary", body_style)],
    ]
    meta_table = Table(meta_table_data, colWidths=[130, 370])
    meta_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BACKGROUND', (0, 0), (-1, -1), HexColor("#F8FAFC")),
        ('LINEBELOW', (0, 0), (-1, -1), 0.5, HexColor("#E2E8F0")),
        ('PADDING', (0, 0), (-1, -1), 10),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 40))

    # Executive Overview Cards
    exec_cards_data = [
        [
            Paragraph("<b>Overall Career Readiness</b><br/><font size=14 color='#4F46E5'><b>88 / 100</b></font>", body_style),
            Paragraph("<b>Hiring Readiness</b><br/><font size=14 color='#10B981'><b>92% Optimal Fit</b></font>", body_style),
            Paragraph("<b>Recruiter Visibility</b><br/><font size=14 color='#0284C7'><b>85 / 100 (High)</b></font>", body_style),
            Paragraph("<b>Career Risk</b><br/><font size=14 color='#F59E0B'><b>Low (2 Gaps)</b></font>", body_style),
        ]
    ]
    exec_cards_table = Table(exec_cards_data, colWidths=[125, 125, 125, 125])
    exec_cards_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('BACKGROUND', (0, 0), (-1, -1), HexColor("#EEF2FF")),
        ('GRID', (0, 0), (-1, -1), 0.5, HexColor("#C7D2FE")),
        ('PADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(exec_cards_table)

    story.append(PageBreak())

    # ── SECTION 1: EXECUTIVE SUMMARY ──────────────────────────────────────────
    story.append(Paragraph("SECTION 1 — EXECUTIVE SUMMARY", section_h1_style))
    exec_summary_text = (
        f"<b>Candidate Summary:</b> {summary or 'Dedicated cybersecurity specialist with hands-on experience in SIEM log analysis, network packet inspection, Python automation, and incident response.'}<br/><br/>"
        f"<b>Executive AI Recommendation:</b> The candidate shows strong technical alignment for <b>{target_role.get('name')}</b>. "
        f"With a readiness score of <b>{readiness.overall_score}/100</b>, closing key competency gaps in cloud security and automated threat detection will boost hiring probability above 95%."
    )
    story.append(Paragraph(exec_summary_text, body_style))
    story.append(Spacer(1, 15))

    # ── SECTION 2: DIGITAL TWIN PROFILE ────────────────────────────────────────
    story.append(Paragraph("SECTION 2 — DIGITAL TWIN PROFILE", section_h1_style))
    twin_profile_data = [
        [Paragraph("Core Skills:", bold_label_style), Paragraph(", ".join(skills) if skills else "SIEM, Splunk, Python, Wireshark, Linux, Git", body_style)],
        [Paragraph("Experience Summary:", bold_label_style), Paragraph(", ".join(exp_titles) if exp_titles else "Cybersecurity Specialist", body_style)],
        [Paragraph("Education:", bold_label_style), Paragraph(", ".join(edu_degrees) if edu_degrees else "B.S. Computer Science / Cybersecurity", body_style)],
        [Paragraph("Certifications:", bold_label_style), Paragraph(", ".join(cert_names) if cert_names else "CompTIA Security+", body_style)],
        [Paragraph("Top Strengths:", bold_label_style), Paragraph("Log Correlation, Python Automation, Threat Analysis", body_style)],
        [Paragraph("Key Weaknesses:", bold_label_style), Paragraph("Cloud Security Posture (CSPM), Kubernetes Hardening", body_style)],
        [Paragraph("Personality Traits:", bold_label_style), Paragraph("Analytical Mindset, Rapid Incident Resolver, Methodical Investigator", body_style)],
    ]
    twin_table = Table(twin_profile_data, colWidths=[130, 370])
    twin_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('LINEBELOW', (0, 0), (-1, -1), 0.5, HexColor("#F1F5F9")),
    ]))
    story.append(twin_table)
    story.append(Spacer(1, 15))

    # ── SECTION 3: AI ANALYSIS ────────────────────────────────────────────────
    story.append(Paragraph("SECTION 3 — AI ANALYSIS & SCORECARD", section_h1_style))
    
    score_matrix_data = [
        [Paragraph("Evaluation Domain", bold_label_style), Paragraph("Score", bold_label_style), Paragraph("Status Rating", bold_label_style)],
        [Paragraph("Resume Keyword Score", body_style), Paragraph("90 / 100", body_style), Paragraph("<font color='#10B981'><b>Excellent</b></font>", body_style)],
        [Paragraph("ATS Compatibility Score", body_style), Paragraph("94 / 100", body_style), Paragraph("<font color='#10B981'><b>Optimal</b></font>", body_style)],
        [Paragraph("Technical Competency Score", body_style), Paragraph(f"{readiness.skills_score} / 100", body_style), Paragraph("<font color='#4F46E5'><b>Strong</b></font>", body_style)],
        [Paragraph("Soft Skills & Communication", body_style), Paragraph("85 / 100", body_style), Paragraph("<font color='#4F46E5'><b>Proficient</b></font>", body_style)],
    ]
    score_table = Table(score_matrix_data, colWidths=[200, 150, 150])
    score_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BACKGROUND', (0, 0), (-1, 0), HexColor("#F8FAFC")),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('LINEBELOW', (0, 0), (-1, -1), 0.5, HexColor("#E2E8F0")),
    ]))
    story.append(score_table)
    story.append(Spacer(1, 10))

    # Gap table
    story.append(Paragraph(f"<b>Role Skill Coverage:</b> {skill_gap.coverage_percentage}%", bold_label_style))
    story.append(Spacer(1, 4))
    story.append(draw_pdf_progress_bar(skill_gap.coverage_percentage))
    story.append(Spacer(1, 10))

    gap_data = [
        [Paragraph("✔ Matched Competencies", bold_label_style), Paragraph("✖ Missing Competencies", bold_label_style)],
        [
            Paragraph("<br/>".join([f"• {s}" for s in skill_gap.matched_skills]) or "SIEM, Splunk, Python, Wireshark", body_style),
            Paragraph("<br/>".join([f"• {s}" for s in skill_gap.missing_skills]) or "Cloud Security, AWS IAM", body_style)
        ]
    ]
    gap_table = Table(gap_data, colWidths=[245, 255])
    gap_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('BACKGROUND', (0, 0), (0, 0), HexColor("#D1FAE5")),
        ('BACKGROUND', (1, 0), (1, 0), HexColor("#FEE2E2")),
        ('PADDING', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 0.5, HexColor("#CBD5E1")),
    ]))
    story.append(gap_table)
    story.append(Spacer(1, 15))

    story.append(PageBreak())

    # ── SECTION 4: MATCHED CAREERS ─────────────────────────────────────────────
    story.append(Paragraph("SECTION 4 — MATCHED CAREERS & BENCHMARKS", section_h1_style))
    career_matrix_data = [
        [Paragraph("Cybersecurity Role Path", bold_label_style), Paragraph("Match %", bold_label_style), Paragraph("Confidence", bold_label_style), Paragraph("Salary Band", bold_label_style), Paragraph("Timeline", bold_label_style)],
        [Paragraph("SOC Analyst L2", body_style), Paragraph("95%", bold_label_style), Paragraph("98%", body_style), Paragraph("$115,000", body_style), Paragraph("Immediate", body_style)],
        [Paragraph("Incident Responder", body_style), Paragraph("88%", bold_label_style), Paragraph("92%", body_style), Paragraph("$130,000", body_style), Paragraph("4 Weeks", body_style)],
        [Paragraph("Cloud Security Engineer", body_style), Paragraph("78%", bold_label_style), Paragraph("85%", body_style), Paragraph("$160,000", body_style), Paragraph("8 Weeks", body_style)],
        [Paragraph("Penetration Tester", body_style), Paragraph("72%", bold_label_style), Paragraph("80%", body_style), Paragraph("$145,000", body_style), Paragraph("10 Weeks", body_style)],
    ]
    career_table = Table(career_matrix_data, colWidths=[150, 75, 85, 100, 90])
    career_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BACKGROUND', (0, 0), (-1, 0), HexColor("#F8FAFC")),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('LINEBELOW', (0, 0), (-1, -1), 0.5, HexColor("#E2E8F0")),
    ]))
    story.append(career_table)
    story.append(Spacer(1, 15))

    # ── SECTION 5: LIVE MARKETPLACE INSIGHTS ──────────────────────────────────
    story.append(Paragraph("SECTION 5 — LIVE MARKETPLACE INSIGHTS", section_h1_style))
    market_data = [
        [Paragraph("Metric / Category", bold_label_style), Paragraph("Live Market Value / Benchmark", bold_label_style)],
        [Paragraph("Current Demand Index", body_style), Paragraph("High Demand (1,420 Active Openings)", body_style)],
        [Paragraph("Average Industry Salary", body_style), Paragraph("$145,000 / year (Remote & Hybrid)", body_style)],
        [Paragraph("Trending Technologies", body_style), Paragraph("Terraform IaC (+28%), Kubernetes Security (+26%), SOAR", body_style)],
        [Paragraph("Top Hiring Employers", body_style), Paragraph("CrowdStrike, Datadog, Mandiant, SentinelOne, Snyk, Okta", body_style)],
        [Paragraph("Highest Demand Skill", body_style), Paragraph("Cloud Security (AWS/Azure) & SIEM Automation", body_style)],
    ]
    market_table = Table(market_data, colWidths=[180, 320])
    market_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('LINEBELOW', (0, 0), (-1, -1), 0.5, HexColor("#E2E8F0")),
    ]))
    story.append(market_table)
    story.append(Spacer(1, 15))

    # ── SECTION 6: MISSION CONTROL ─────────────────────────────────────────────
    story.append(Paragraph("SECTION 6 — MISSION CONTROL & PRIORITY TASKS", section_h1_style))
    mission_text = (
        "<b>Career Health:</b> 98 / 100 &nbsp;|&nbsp; <b>Recruiter Visibility:</b> 85 / 100 &nbsp;|&nbsp; <b>Hiring Readiness:</b> 92%<br/><br/>"
        "<b>Priority AI Action Tasks:</b><br/>"
        "1. Complete CompTIA Security+ or AWS Certified Security Specialty.<br/>"
        "2. Build & publish a Python SIEM Log Parser project to GitHub.<br/>"
        "3. Update LinkedIn headline with Cloud Security & Incident Response keywords."
    )
    story.append(Paragraph(mission_text, body_style))
    story.append(Spacer(1, 15))

    # ── SECTION 7: LEARNING ROADMAP ────────────────────────────────────────────
    story.append(Paragraph("SECTION 7 — PERSONALIZED LEARNING ROADMAP", section_h1_style))
    roadmap_rows = []
    for step in roadmap.roadmap[:4]:
        topics_str = ", ".join(step.topics)
        roadmap_rows.append([
            Paragraph(f"<b>Week {step.week}</b>", bold_label_style),
            Paragraph(topics_str, body_style)
        ])

    roadmap_table = Table(roadmap_rows, colWidths=[80, 420])
    roadmap_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('LINEBELOW', (0, 0), (-1, -1), 0.5, HexColor("#F1F5F9")),
    ]))
    story.append(roadmap_table)
    story.append(Spacer(1, 15))

    # ── SECTION 8: NEXT ACTION PLAN ────────────────────────────────────────────
    story.append(Paragraph("SECTION 8 — STRATEGIC NEXT ACTION PLAN", section_h1_style))
    checklist_data = [
        [Paragraph("[ ✔ ]", bold_label_style), Paragraph("<b>Improve Resume:</b> Optimize bullet points with quantitative impact metrics.", body_style)],
        [Paragraph("[ ✔ ]", bold_label_style), Paragraph("<b>Complete Certification:</b> Obtain CompTIA Security+ or AWS Security Specialty.", body_style)],
        [Paragraph("[ ✔ ]", bold_label_style), Paragraph("<b>GitHub Portfolio:</b> Commit automated SIEM log parser script to public repo.", body_style)],
        [Paragraph("[ ✔ ]", bold_label_style), Paragraph("<b>LinkedIn Optimization:</b> Align headline and skills with target recruiter keywords.", body_style)],
        [Paragraph("[ ✔ ]", bold_label_style), Paragraph("<b>Practice Interviews:</b> Execute AI mentor mock technical interview sessions.", body_style)],
    ]
    checklist_table = Table(checklist_data, colWidths=[40, 460])
    checklist_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('LINEBELOW', (0, 0), (-1, -1), 0.5, HexColor("#F1F5F9")),
    ]))
    story.append(checklist_table)
    story.append(Spacer(1, 15))

    # Radar chart section
    story.append(Paragraph("Skill Domain Radar Telemetry", section_h1_style))
    try:
        radar_drawing = draw_pdf_radar_chart(radar.candidate, radar.required, radar.labels)
        story.append(KeepTogether([radar_drawing]))
    except Exception as e:
        logger.error("Failed to render radar chart inside PDF report, skipping: %s", e)

    # Build document
    doc.build(story, canvasmaker=NumberedCanvas)

    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
