"""
Pydantic schemas for the AI Career Mentor feature.
"""

from typing import Any, Optional
from pydantic import BaseModel, Field


class CareerMentorRequest(BaseModel):
    """Payload sent by client containing user question and candidate profile context."""

    message: Optional[str] = Field(default=None, description="User question / message for the mentor.")
    question: Optional[str] = Field(default=None, description="User question (alternative field name).")
    role_id: str = Field(default="security-analyst", description="Selected target cybersecurity role ID.")
    target_role: Any = Field(default=None, description="Target role object or ID.")
    resume_data: Any = Field(default=None, description="Parsed resume data object.")
    skills: list[str] = Field(default=[], description="Detected skill names.")
    name: str = Field(default="", description="Candidate name.")
    email: str = Field(default="", description="Candidate email.")
    phone: str = Field(default="", description="Candidate phone number.")
    summary: str = Field(default="", description="Candidate summary paragraph.")
    exp_titles: list[str] = Field(default=[], description="Parsed job titles.")
    exp_descriptions: list[str] = Field(default=[], description="Parsed job descriptions.")
    exp_durations: list[str] = Field(default=[], description="Parsed job durations.")
    edu_degrees: list[str] = Field(default=[], description="Parsed degrees.")
    cert_names: list[str] = Field(default=[], description="Parsed certifications.")

    @property
    def prompt_message(self) -> str:
        """Return non-empty user prompt string."""
        if self.message and self.message.strip():
            return self.message.strip()
        if self.question and self.question.strip():
            return self.question.strip()
        return "Hi"


class CareerMentorResponse(BaseModel):
    """Personalized markdown answer generated by CareerPilot AI."""

    success: bool = Field(default=True, description="Indicates whether request succeeded.")
    answer: str = Field(..., description="Personalized mentor answer in markdown format.")
    reply: Optional[str] = Field(default=None, description="Alias field for answer.")
    error: Optional[str] = Field(default=None, description="Human-readable error details if failed.")
